blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/yamiSukehiro2907/studi.io/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 📧 Email Support
    url: mailto:studi.io2907@gmail.com
    about: For private inquiries or security concerns
  - name: 📚 Documentation
    url: https://github.com/yamiSukehiro2907/studi.io#readme
    about: Check our comprehensive README and setup guides
  - name: 🔒 Security Issues
    url: https://github.com/yamiSukehiro2907/studi.io/security/policy
    about: Report security vulnerabilities privately
